name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        make

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure

  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        cmake --build .

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure 